# Site
repository: joaodelgado/joaodelgado.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: João Delgado
title: Software Engineer
email: joaomtdelgado@gmail.com
# email_title: Personal
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: joaodelgado.github.io
# website_title: Website

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username:  joaodelgado
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: joão-delgado-a55088aa
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
  # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello!

  I'm a web developer with 8 years of experience, specializing in backend services.

  The technologies I have the most experience with are **Java**, **Spring**, **Postgres**, **ElasticSearch**, and **Kafka**.

content:
  # - title: Projects # Title for the section
    # layout: list # Type of content section (list/text)
    # content:
      # - layout: left
        # border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # # other value (or no value) means no border will be displayed
        # title: Project name
        # link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # link_text: Link Text
        # additional_links:
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            # icon: fab fa-github
            # url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
            # icon: fab fa-github
            # url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        # quote: >
          # Short overview of the project (optional)
        # description: | # this will include new lines to allow paragraphs
          # Description about the work on/with the project
  - title: Experience
    layout: list
    content:

      - layout: left
        title: Staff Engineer
        sub_title: <a href="https://five9.com">Five9</a>
        caption: December 2024 - Present
        quote: >
          Work Force Optimization
        description: |
          Starting a brand new adventure, in a new business context - Contact Centers.

          Currently focusing on call-recording related services, where the main challenges are:
            - Ensuring a reliable and resilient recording environment
            - Modernization of a legacy application to an event-based architecture, running on a cloud environment.

          The tech stack includes mainly:
            - **Java** with **SpringBoot**
            - Both on-premise and cloud deployments (using **GCP** and **Kubernetes**)

      - layout: left
        border: weak
        title: Principal Engineer
        sub_title: <a href="https://jumia.com">Jumia</a>
        caption: January 2023 - December 2024
        quote: >
          Vendor platforms & Marketing
        description: |
          Modernizing Jumia's vendor platform from a legacy **PHP** application into more scalable **Java** microservices, with the help of 3 development teams.
          It involves predominantly catalog and order management and the main tech stack is **Spring Boot**, **Postgres**, **ElasticSearch**, and **Kafka**.

          The primary challenge is its overall scale:
            - a large system with almost 15 years of historical data,
            - tens of thousands of integrated vendors,
            - hundreds of millions of products,
            - across more than 10 ventures.

          For the last few months I expanded my scope to Jumia's marketing services, responsible mainly for handling marketing communications.
          This set of services was using **Go** with **Gin** and **GORM**, and **Kubernetes** for all deployments.

      - layout: left
        border: weak
        title: Staff Engineer
        sub_title: <a href="https://jumia.com">Jumia</a>
        caption: August 2019 - December 2022
        quote: >
          Miscellaneous projects
        description: |
          Integrated a team responsible for various major projects in Jumia, all using **Spring Boot**. I was the technical leader for services handling:
            - Authentication and authorization for all internal tools,
            - Transactional communications.

          I was also involved from the ground up in projects responsible for:
            - General document printing for transactional systems (e.g. shipping labels, invoices, etc),
            - Integration with local tax authorities in Uganda and Egypt.

          I highlight the Search Project, to which I made my main contribution.
          This is an availability and performance-critical service that handles all the search and navigation traffic across the Jumia websites.

          Here I had the opportunity to work on top of **ElasticSearch** and **Kafka**, with a big focus on metrics, AB testing, and data-driven development.

      - layout: left
        border: weak
        title: Team Leader
        sub_title: <a href="https://jumia.com">Jumia</a>
        caption: December 2017 - August 2019
        quote: >
          Fulfillment - Order and Warehouse management
        description: |
          Led a team of around seven people, responsible for warehouse and order management systems in a multitude of technology stacks.

          I inherited a monolith service in **PHP** that was being rewritten into two separate sets of microservices: one using the **Play Framework**, and another using **Spring Boot**.

          I also had the opportunity to interact with other databases like **MariaDB** and **MongoDB** and started using **Docker** for deployments and CI builds.

      - layout: left
        border: weak
        title: Web developer
        sub_title: <a href="https://jumia.com">Jumia</a>
        caption: October 2015 - December 2017
        quote: >
          Logistics - Package management
        description: |
          Worked as a full-stack developer for a logistics system that managed all package deliveries in Jumia.
          The goal of this project was to revamp the way Jumia handled package and delivery management, in **Java**.

          I had my first real contact with **Spring**, learned about message brokers with **RabbitMQ**, and SQL databases in production with **PostgreSQL**.

      - layout: left
        border: weak
        title: Intern
        sub_title: <a href="https://www.geolink.pt/">Geolink</a>
        caption: July 2014 - September 2015
        # link: https://www.geolink.pt/
        quote: Invoicing system
        description: | # this will include new lines to allow paragraphs
          Worked as an intern for a Portuguese company developing software for taxi dispatching, while I was writing my master's thesis.

          During this year, I worked on an invoicing system to be used for issuing invoices for taxi rides and integrating them with Portuguese tax authorities.
          This was my first interaction with web development (in **Python**) and started to get some experience with web frameworks and ORMs (using **Flask** and **SQLAlchemy**).
          <div class="print-only page-break"></div>

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: <a href="https://sigarra.up.pt/fcup/en/CUR_GERAL.CUR_VIEW?pv_ano_lectivo=2023&pv_curso_id=870">Master's in Network and Information Systems Engineering</a>
        sub_title: Faculdade de Ciências da Universidade do Porto
        caption: 2010-2015

  - title: When I'm not working
    layout: text
    content: | # this will include new lines to allow paragraphs
      Outside work, I love to travel.
      I'm currently on a mission to visit 40 different countries before I turn 40.
      I'm also enthusiastic about photography, climbing, and orienteering.

      I've also been recently introduced to the fascinating worlds of coffee and wine.

      While I'm still sitting at my desk, I like to explore some different programming languages for small toy projects.
      Recently, I fell in love with Rust and it's been hard to let it go.

# Footer
# footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
